# -*- coding: utf-8 -*-

#------------------------------------------------------------------------------
# Event types
#------------------------------------------------------------------------------

EVT_MISSION_PLAYING = 'MIS_PLY'
EVT_MISSION_BEGIN = 'MIS_BGN'
EVT_MISSION_END = 'MIS_END'
EVT_MISSION_WON = 'MIS_WON'
EVT_TARGET_END = 'TGT_END'

EVT_CONNECTED = 'CON'
EVT_DISCONNECTED = 'DISCON'
EVT_WENT_TO_MENU = 'WENT_MENU'
EVT_SELECTED_ARMY = 'SEL_ARMY'

EVT_WEAPONS_LOADED = 'WPN_LOAD'
EVT_SEAT_OCCUPIED = 'SEL_SEAT'
EVT_BAILED_OUT = 'BAIL'
EVT_PARACHUTE_OPENED = 'CHUTE_OPEN'
EVT_TOGGLE_LANDING_LIGHTS = 'LAND_LGHT'
EVT_TOGGLE_WINGTIP_SMOKES = 'SMOKES'
EVT_TOOK_OFF = 'TKOFF'
EVT_WOUNDED = 'WNDED'
EVT_HEAVILY_WOUNDED = 'H_WNDED'
EVT_KILLED = 'KLD'
EVT_KILLED_BY_USER = 'KLD_BY_USR'
EVT_CAPTURED = 'CAPT'
EVT_CRASHED = 'CRSH'
EVT_LANDED = 'LANDED'
EVT_DESTROYED_BLD = 'DSTR_BLD'
EVT_DESTROYED_TREE = 'DSTR_TREE'
EVT_DESTROYED_STATIC = 'DSTR_STTC'
EVT_DESTROYED_BRIDGE = 'DSTR_BRDG'
EVT_DAMAGED_ON_GROUND = 'DMG_ON_GND'
EVT_DAMAGED_BY_USER = 'DMG_BY_USR'
EVT_DAMAGED_SELF = 'DMG_SELF'
EVT_SHOT_DOWN_SELF = 'SHT_SELF'
EVT_SHOT_DOWN_BY_USER = 'SHT_BY_USR'
EVT_SHOT_DOWN_BY_STATIC = 'SHT_BY_STTC'
